import type { Metadata } from 'next'

import { AiOutlineInstagram, AiOutlineDown, AiOutlineTwitter, AiFillYoutube, AiOutlineDribbble } from "react-icons/ai";

import Image from "next/image";
import logo from "../images/logo.png"
import logowhite from "../images/logo-white.png"

export const metadata: Metadata = {
  title: 'Front End',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <header className="py-6 bg-custom-blue hidden md:block">
        <div className="container flex justify-between mx-auto px-10">
          <Image
            alt=""
            src={logo}
          />
          <div className='flex'>
            <nav className="flex items-center justify-between" >
              <a href="#" className="mx-5 text-indigo-900 hover:text-blue-700">Home</a>
              <div className="flex items-center mx-5" >
                <a href="#" className="mx-1 text-indigo-900 hover:text-blue-700">Landings </a>
                <AiOutlineDown size="10" color="bg-custom-blue" />
              </div>
              <div className="flex items-center mx-5">
                <a href="#" className="mx-1 text-indigo-900 hover:text-blue-700">Pages </a>
                <AiOutlineDown size="10" color="bg-custom-blue" />
              </div>
              <a href="#" className="mx-5 text-indigo-900 hover:text-blue-700">Docs</a>
              <a href="#" className="mx-5 text-indigo-900 hover:text-blue-700">Help</a>
            </nav>
            <button
              className="px-4 font-bold text-indigo-800 border border-indigo-800 rounded-md "
            >
              Get it now
            </button>
          </div>
        </div>
      </header>

      <>{children}</>

      <footer className="p-4 bg-indigo-800 ">
        <div className="container flex flex-col mx-auto md:flex-row md:justify-between md:items-center">
          <div className='text-xs font-normal text-white'>© 2022 PRO POS. All rights reserved</div>
          <Image className='hidden md:block'

            alt=""
            src={logowhite}
          />
          <div className='flex items-center pt-5 md:justify-between'>

            <div className='w-7 h-7 mx-1 bg-gray-300 rounded-full flex items-center justify-center text-white'>
              <AiOutlineInstagram size="18" className="mx-1 text-white" />
            </div>
            <div className='w-7 h-7 mx-1 bg-gray-300 rounded-full flex items-center justify-center text-white'>
              <AiOutlineDribbble size="18" className="mx-1 text-white" />
            </div>
            <div className='w-7 h-7 mx-1 bg-gray-300 rounded-full flex items-center justify-center text-white'>
              <AiOutlineTwitter size="18" className="mx-1 text-white" />
            </div>
            <div className='w-7 h-7 mx-1 bg-gray-300 rounded-full flex items-center justify-center text-white'>
              <AiFillYoutube size="18" className="mx-1 text-white" />
            </div>

          </div>
        </div>
      </footer>
    </>
  )
}